steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - .
  - -t
  - us-docker.pkg.dev/$PROJECT_ID/rookie/${_APP_TYPE}
  - -f
  - ./Dockerfile
images:
- 'us-docker.pkg.dev/$PROJECT_ID/rookie/${_APP_TYPE}'